//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDormitoryManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Receipt
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID_Receipt { get; set; }
        public Nullable<int> TenantReceipt { get; set; }
        public Nullable<decimal> PayLiving { get; set; }
        public Nullable<decimal> PayAddService { get; set; }
        public Nullable<System.DateTime> DataPay { get; set; }

        [ForeignKey("TenantReceipt")]
        public virtual Tenant Tenant { get; set; }
    }
}
